ROR_Project/hiptime/config/routes.rb
Rails.application.routes.draw do

  resources :items
  root 'items#index'
end

ROR_Project/hiptime/app/models/item.rb
class Item < ActiveRecord::Base
end

ROR_Project/hiptime/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ROR_Project/hiptime/app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.order('created_at DESC')
  end

  def show

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render('edit')
    end
  end

  def destroy
    @item.destroy()
    redirect_to root_path

  end


  private
  def item_params
    params.require(:item).permit(:title, :description)
  end

  def find_item
    @item = Item.find(params[:id])
  end

end

ROR_Project/hiptime/app/helpers/application_helper.rb
module ApplicationHelper
end

ROR_Project/hiptime/app/helpers/items_helper.rb
module ItemsHelper
end

ROR_Project/hiptime/app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
    <%= f.input :title, label: "item" %>
    <%= f.input :description %>
    <%= f.button :submit %>
<% end %>

ROR_Project/hiptime/app/views/items/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit todo item </h1>

  <%= render 'form' %>
</div>

ROR_Project/hiptime/app/views/items/index.html.erb
<% @items.each do |item| %>

    <h2> <%= link_to item.title, item %></h2>

    <p>
      <%= item.description %></p>

<% end %>

<%= link_to 'New Item', new_item_path %>

ROR_Project/hiptime/app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>New todo item </h1>

  <%= render 'form' %>
</div>

ROR_Project/hiptime/app/views/items/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <h2><%= @item.title %></h2>

  <p> <%= @item.description %></p>

  <div class="col-md-4 col-md-offset-4">
    <%= link_to 'Back', root_path %>
    <%= link_to 'Edit', edit_item_path %>
    <%= link_to 'Delete', item_path(@item), method: :delete, data: {confirm: 'Are you sure?'} %>
  </div>

</div>

ROR_Project/hiptime/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hiptime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>